import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'

import { useGoogleOneTapLogin } from '@react-oauth/google'

export default function Home () {
  useGoogleOneTapLogin({
    onSuccess: async credentialResponse => {
      console.log(credentialResponse)
      await axios
        .post('https://ideas-backend-v2.herokuapp.com/auth/google', {
          token: credentialResponse.credential
        })
        .then(res => {
          console.log(res.data)
        })
    },
    onError: () => {
      console.log('Login Failed')
    }
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>DSC Ideas Hub</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to DSC Ideas Hub!
        </h1>
      </main>
    </div>
  )
}
