import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'

import { GoogleLogin, useGoogleOneTapLogin } from '@react-oauth/google'

export default function Home () {
  useGoogleOneTapLogin({
    onSuccess: async credentialResponse => {
      await axios
        .post('https://ideas-backend-v2.herokuapp.com/auth/google', {
          token: credentialResponse.credential
        })
        .then(res => {
          console.log(res.data)
        })
    },
    onError: () => {
      console.log('Login Failed')
    }
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>DSC Ideas Hub</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <GoogleLogin
        onSuccess={async (res) => {
          await axios
            .post('https://ideas-backend-v2.herokuapp.com/auth/google', {
              token: res.credential
            })
            .then(res => {
              console.log(res.data)
            })
        }}
      />

      <div className={styles.main}>
        <h1 className={styles.title}>
          Welcome to DSC Ideas Hub!
        </h1>
        <p>Islands/Castles/Something

          Can be integrated with a channel on a discord server via a helper bot.
          Use NFTs and web3 for virtual transactions.
          Incorporate gather.town type of functionality (specifically the video thing)
          Usecase: hackathon announcements.

          Gamifying tasks and goals kinda like Habitica
          Incentive system with in game items/rewards
        </p>
        <p>"Everything Begins With An Idea" – Earl Nightingale</p>
      </div>
    </div>
  )
}
