import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { GoogleLogin } from '@react-oauth/google';
import { useGoogleOneTapLogin } from '@react-oauth/google';

export default function Home () {
  useGoogleOneTapLogin({
    onSuccess: credentialResponse => {
        console.log(credentialResponse.credential);
    },
    onError: () => {
        console.log('Login Failed')
    }
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>DSC Ideas Hub</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>DSC Ideas Hub!</a>
        </h1>
      </main>
    </div>
  )
}
